server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: admin
          # lb代表从注册中心获取服务，且已负载均衡方式转发
          uri: lb://admin
          predicates:
            - Path=/admin/**
          # 加上StripPrefix=1，否则转发到后端服务时会带上consumer前缀
          filters:
            - StripPrefix=1
      default-filters:
        # 熔断降级配置,全局断路器
        - name: Hystrix
          args:
            name: default
            fallbackUri: forward:/defaultFallback
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000 # 10s 服务连不上触发回滚

# 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always