server:
  port: 9999

spring:
  application:
    name: eureka #需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name 。

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    registerWithEureka: false #false表示不向服务中心注册自己
    fetchRegistry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与eureka service交互的地址查询服务和注册服务